### ISSUE TITLE
Add libre license

### ISSUE THREAD

**Issue by throwaway1037** [dreamsmasher/site-haskell-source#1]
Please may the project be released under a [libre](https://freedomdefined.org) license?

I'd recommend CC-BY-SA-4.0-Int-or-later for writings, and GNU-AGPL-v3-or-later for code.

**Comment by dreamsmasher** [comment]
Good call. There's a bit of  ~~cargo-culted~~ inlined code that I'll have to look into wrt. licensing but CC for the writing sounds about right. Thank you!
